### ISSUE TITLE
War example

### ISSUE THREAD

**Issue by jeusdi** [nemerosa/versioning#34]
I'm not quite understing how to merge the information the plugin provides in order to create for example a versional war filename.

Could you provide a short example?

**Comment by dcoraboeuf** [comment]
Hi @jeusdi,

It depends what you really want to achieve, but in general, you just have to use the information contained in the `versioning.info` object inside your regular Gradle script.

So, for example, to set the WAR name using the `display` version, you could use:

```groovy
war {
    archiveName "mywar-${versioning.info.display}.war"
}
```

Although, in my opinion, this is irrelevant since by default, the WAR name will include the project version, and the following should be enough:

```groovy
version = versioning.info.display
```

More useful would be to use the versioning info to generate information in the Manifest file of the WAR for example:

```groovy
war {
   manifest {
      attributes 'Implementation-Version': versioning.info.display
   }
}
```

As you see, as long as you know how to access the `versioning.info`, you can inject versioning data basically everywhere you need in your Gradle script.

I hope it answers your question,
Damien.
